//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Inventory_SystemEntities : DbContext
    {
        public Inventory_SystemEntities()
            : base("name=Inventory_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Issue> Issues { get; set; }
        public virtual DbSet<IssueDetail> IssueDetails { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Lkup_Fin_Year> Lkup_Fin_Year { get; set; }
        public virtual DbSet<Lkup_Item_Status> Lkup_Item_Status { get; set; }
        public virtual DbSet<Lkup_Payment_Reason> Lkup_Payment_Reason { get; set; }
        public virtual DbSet<Lkup_Payment_Type> Lkup_Payment_Type { get; set; }
        public virtual DbSet<Lkup_Receipt_Type> Lkup_Receipt_Type { get; set; }
        public virtual DbSet<Lkup_Stock_Type> Lkup_Stock_Type { get; set; }
        public virtual DbSet<Lkup_UOI> Lkup_UOI { get; set; }
        public virtual DbSet<Lkup_User_Roles> Lkup_User_Roles { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<StockDetail> StockDetails { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
