//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueDetail
    {
        public decimal ISSUEDETAILS_ID { get; set; }
        public decimal ISSUE_ID { get; set; }
        public decimal ITEM { get; set; }
        public decimal REQUESTED_QTY { get; set; }
        public string APPROVED_QTY { get; set; }
        public decimal ISSUED_QTY { get; set; }
        public decimal ITEM_STATUS { get; set; }
        public decimal ITEM_UOI { get; set; }
        public decimal UNIT_PRICE { get; set; }
        public decimal TOTAL_PRICE { get; set; }
        public string NOTES { get; set; }
    
        public virtual Issue Issue { get; set; }
        public virtual Item Item1 { get; set; }
        public virtual Lkup_Item_Status Lkup_Item_Status { get; set; }
        public virtual Lkup_UOI Lkup_UOI { get; set; }
    }
}
