//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Issue()
        {
            this.IssueDetails = new HashSet<IssueDetail>();
        }
    
        public decimal ISSUE_ID { get; set; }
        public System.DateTime ISSUE_DATE { get; set; }
        public decimal REQ_EMPLOYEE { get; set; }
        public decimal ISSUE_TYPE { get; set; }
        public decimal FROM_STOCK { get; set; }
        public string NOTES { get; set; }
        public decimal FIN_YEAR { get; set; }
        public string ACTIVE { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Lkup_Stock_Type Lkup_Stock_Type { get; set; }
        public virtual Stock Stock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueDetail> IssueDetails { get; set; }
        public virtual Lkup_Fin_Year Lkup_Fin_Year { get; set; }
    }
}
