//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.IssueDetails = new HashSet<IssueDetail>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.StockDetails = new HashSet<StockDetail>();
        }
    
        public decimal ITEM_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public decimal ITEM_CATEGORY { get; set; }
        public decimal ITEM_UOI { get; set; }
        public string ITEM_VENDOR { get; set; }
        public string ITEM_DESCRIPTON { get; set; }
        public string ITEM_NAME { get; set; }
        public string ACTIVE { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueDetail> IssueDetails { get; set; }
        public virtual Lkup_UOI Lkup_UOI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockDetail> StockDetails { get; set; }
    }
}
