//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public decimal ORDER_ID { get; set; }
        public System.DateTime ORDER_DATE { get; set; }
        public decimal SUPPLIER { get; set; }
        public decimal PAYMENT_TYPE { get; set; }
        public string ORDER_PERIOD { get; set; }
        public decimal RECEIPT_TYPE { get; set; }
        public string NOTES { get; set; }
        public decimal FIN_YEAR { get; set; }
        public string ACTIVE { get; set; }
    
        public virtual Lkup_Payment_Type Lkup_Payment_Type { get; set; }
        public virtual Lkup_Receipt_Type Lkup_Receipt_Type { get; set; }
        public virtual Supplier Supplier1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Lkup_Fin_Year Lkup_Fin_Year { get; set; }
    }
}
