//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public decimal PAYMENT_ID { get; set; }
        public decimal PAYMENT_REASON { get; set; }
        public System.DateTime PAYMENT_DATE { get; set; }
        public decimal PAYMENT_AMOUNT { get; set; }
        public string NOTES { get; set; }
        public decimal FIN_YEAR { get; set; }
        public string ACTIVE { get; set; }
    
        public virtual Lkup_Payment_Reason Lkup_Payment_Reason { get; set; }
        public virtual Lkup_Fin_Year Lkup_Fin_Year { get; set; }
    }
}
