//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockDetail
    {
        public decimal STOCKDETAIL_ID { get; set; }
        public decimal STOCK_ID { get; set; }
        public decimal ITEM { get; set; }
        public decimal QTY { get; set; }
        public decimal ITEM_STATUS { get; set; }
        public decimal UNIT_BUY_PRICE { get; set; }
        public decimal UNIT_SELL_PRICE { get; set; }
        public decimal TOTAL_BUY_PRICE { get; set; }
        public decimal TOTAL_SELL_PRICE { get; set; }
        public string NOTES { get; set; }
        public decimal DOC_ID { get; set; }
    
        public virtual Item Item1 { get; set; }
        public virtual Lkup_Item_Status Lkup_Item_Status { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
