//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public decimal USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public decimal USER_ROLE { get; set; }
        public string PASSWORD_HINT { get; set; }
        public string ACTIVE { get; set; }
    
        public virtual Lkup_User_Roles Lkup_User_Roles { get; set; }
    }
}
